title = "Roxy configuration TOML"

[statsite]
  enabled = true
  ip = "0.0.0.0"
  port = 8125

[roxy]
  ip = "127.0.0.1"
  port = 8088
  p95 = 4.0
  bg_procs = 5

[riak]
  ip = "127.0.0.1"
  port = 8087
  pool_size = 25
